- repl/src/main/resources/fake_shell.py
A mock for the `ast.Module` is created in case of running older Python versions (< 3.8). The mocked module will ignore the new `type_ignores` parameter, and pass only the first parameter to the old module.
As already mentioned by Shiquan Wang (the issue reporter), Python 3.8 introduced a change in the API (https://github.com/python/cpython/pull/11645/files), and IPython had a similar problem. The strategy used for this fix is similar to the one utilized by IPython in this PR: https://github.com/ipython/ipython/pull/11593 
JIRA: https://issues.apache.org/jira/projects/LIVY/issues/LIVY-795
Tested locally, using Jupyter notebook to run pyspark commands.
> [LIVY-795] Add support for PySpark with Python >= 3.8 

- client-common/pom.xml
- pom.xml
- repl/pom.xml
- rsc/pom.xml
Use shaded kryo library which causes inconsistencies in asm dependencies. https://issues.apache.org/jira/browse/LIVY-783
Tested on live cluster.
> [LIVY-783] Use shaded kryo library

- pom.xml
Bumps `jackson` versions to 2.12.7 and `jackson-databind` to 2.12.7.1. Closes #364 
Local unit/integration tests.
> Bump jackson to 2.12.7

- pom.xml
LIVY-903 - Address Netty Upgrades for 0.8.0
Upgrade of netty version from 4.1.17 to 4.1.86
Build with unit and integration tests.
Please review https://livy.incubator.apache.org/community/ before opening a pull request.
> LIVY-903 - Address Netty Upgrades for 0.8.0

- client-http/src/test/scala/org/apache/livy/client/http/LivyConnectionSpec.scala
- pom.xml
Bump version of Jetty to latest on the 9.4.x line to 9.4.50.v20221201
Also, address the incompatibility in LivyConnectionSpec.scala to make compatible with new Jetty dependency.
Build with unit and integration tests
> Livy 904 - Address Jetty Dependency Upgrades for 0.8.0

- repl/scala-2.11/src/main/scala/org/apache/livy/repl/SparkInterpreter.scala
- repl/scala-2.12/src/main/scala/org/apache/livy/repl/SparkInterpreter.scala
- repl/src/main/scala/org/apache/livy/repl/AbstractSparkInterpreter.scala
- repl/src/main/scala/org/apache/livy/repl/PythonInterpreter.scala
- repl/src/main/scala/org/apache/livy/repl/ReplDriver.scala
- rsc/src/main/java/org/apache/livy/rsc/driver/RSCDriver.java
* addJar invoked for a running Livy session will add that jar resource to SparkInterpreter classpath in addition to Spark driver classpath.
* addJarOrPyFile signature changed to return the local path to which it was copied. This local path is required to add the same jar resource to SparkInterpreter classpath.
* addFile now goes through appropriate Interpreter based on the interpreter instead of default PythonInterpreter.
https://issues.apache.org/jira/browse/LIVY-889
This patch was tested by adding a Jar on a running Livy session and then trying to load a class from that jar using spark interpreter.
> [LIVY-889] Adding jars to Spark Interpreter classpath on an already running Livy Session

- rsc/src/main/java/org/apache/livy/rsc/driver/RSCDriver.java
- rsc/src/test/java/org/apache/livy/rsc/TestSparkClient.java
When a duplicate file is attempted to be added using LivyClient, duplicate file's addition is skipped and an appropriate warning is logged instead of the old behavior of throwing fatal IOException. This is now consistent with SparkContext's addJar and addFile APIs behavior. 
https://issues.apache.org/jira/browse/LIVY-888
Modified the unit test TestSparkClient#testAddJarsAndFiles to attempt adding a duplicate file, and the test did not fail.
> [LIVY-888] AddJar or AddFile call on a duplicate file should not result in failure for Livy session

- .github/workflows/build-ci-image.yaml
- .github/workflows/integration-tests.yaml
- .github/workflows/unit-tests.yaml
- Adds Several GitHub Workflows
Manual validation in the course of the pull request and new GitHub Actions workflows.
> [LIVY-972] Add GitHub Action for CI image

- docs/rest-api.md
- server/src/main/scala/org/apache/livy/server/interactive/InteractiveSessionServlet.scala
GET /sessions/id/statements returns a list of statements run in a session. However the ordering of the statements are older ones first. Livy could expose a parameter (something like orderBy=latest) that will order the list of statements as latest first.
JIRA: https://issues.apache.org/jira/browse/LIVY-970
Verified manually by creating interactive session and statements via REST API call in a local Yarn cluster.
> [LIVY-970][SERVER] Ordering and pagination support in GET /statement

- client-common/pom.xml
- core/pom.xml
- integration-test/pom.xml
- pom.xml
- repl/pom.xml
- rsc/pom.xml
- scala-api/pom.xml
- server/pom.xml
- thriftserver/server/pom.xml
- thriftserver/session/pom.xml
- Replace log4j with reload4j
- Add exclusions for transitive log4j dependencies including `spark-core`, `hadoop-common` (and others), `zookeeper`, and `apacheds-server`.
- https://issues.apache.org/jira/browse/LIVY-878
- unit/integration tests
> [LIVY-878] Replace log4j with reload4j

- conf/livy.conf.template
- server/src/main/scala/org/apache/livy/LivyConf.scala
- server/src/main/scala/org/apache/livy/server/WebServer.scala
On error, the Livy UI shows verbose output on error pages including the Jetty version number. This could be considered as a security vulnerability. We can make it configurable and avoid sending server version details. The Jetty version is there in every response header as well.
JIRA: https://issues.apache.org/jira/browse/LIVY-974
Verified manually by calling get sessions via REST API call in a local Yarn cluster.
> [LIVY-974][SERVER] Remove verbose output on Livy UI error pages

- conf/livy.conf.template
- server/src/main/scala/org/apache/livy/LivyConf.scala
- server/src/main/scala/org/apache/livy/sessions/Session.scala
- server/src/test/scala/org/apache/livy/sessions/SessionSpec.scala
Recent change in spark required us to fix compatibility issue related to a change on the Spark side.
JIRA: https://issues.apache.org/jira/browse/LIVY-975
Verified manually by creating interactive / batch sessions via REST API call in a local Yarn cluster. Also, we have updated the unit tests.
> [LIVY-975][SERVER] Fix compatibility issue related to a change on the Spark side

- .github/workflows/integration-tests.yaml
- .github/workflows/unit-tests.yaml
- .rat-excludes
- .travis.yml
- README.md
- assembly/assembly.xml
- assembly/pom.xml
- core/scala-2.11/pom.xml
- core/scala-2.12/pom.xml
- coverage/pom.xml
- pom.xml
- repl/scala-2.11/pom.xml
- repl/scala-2.12/pom.xml
- scala-api/scala-2.11/pom.xml
- scala-api/scala-2.12/pom.xml
Added support for specific flags to support hadoop/spark/scala version specific builds.
Ran `mvn install` with the new flags to confirm they work.
>  [LIVY-593] Add flags to support hadoop, spark and scala version specific builds

- .github/workflows/build-ci-image.yaml
- README.md
- dev/docker/README.md
- dev/docker/build-images.sh
- dev/docker/livy-dev-base/Dockerfile
- dev/docker/livy-dev-cluster/conf/livy/livy-env.sh
- dev/docker/livy-dev-cluster/conf/livy/livy.conf
- dev/docker/livy-dev-cluster/conf/livy/log4j.properties
- dev/docker/livy-dev-cluster/conf/master/log4j.properties
- dev/docker/livy-dev-cluster/conf/master/spark-default.conf
- dev/docker/livy-dev-cluster/conf/master/spark-env.sh
- dev/docker/livy-dev-cluster/conf/worker/log4j.properties
- dev/docker/livy-dev-cluster/conf/worker/spark-default.conf
- dev/docker/livy-dev-cluster/conf/worker/spark-env.sh
- dev/docker/livy-dev-cluster/docker-compose.yml
- dev/docker/livy-dev-server/Dockerfile
- dev/docker/livy-dev-spark/Dockerfile
- pom.xml
This PR introduces a docker and docker-compose based integrated environment for local debugging. The environment consists of:
1. Standalone spark cluster consisting of one spark master and one spark worker
2. Livy configured to connect to this standalone cluster
Attached README explains how this integrated environment can be customized to test with private changes.
1. Used `docker-compose up` to bring up the integrated environment
2. Logged into livy container and submitted sample spark and sql statements.
3. Verified spark master, spark worker and livy UIs to be working, verified statements to have succeeded.
4. Verified remote debugging to work by attaching IDE to Livy server
> [LIVY-969] Create docker based integration environment for local debugging

- server/src/main/scala/org/apache/livy/server/batch/BatchSession.scala
- server/src/main/scala/org/apache/livy/server/interactive/InteractiveSession.scala
The following issue occurs:
```
ERROR org.apache.livy.utils.SparkYarnApp: Error whiling refreshing YARN state
java.lang.IllegalStateException: No YARN application is found with tag livy-batch-2-per2hlwa in 120 seconds. This may be because 1) spark-submit fail to submit application to YARN; or 2) YARN cluster doesn't have enough resources to start the application in time. Please check Livy log and YARN log to know the details.
```
if the below configuration parameter is set in YARN:
```
yarn.resourcemanager.application-tag-based-placement.force-lowercase=false
```
We can fix this in InteractiveSession / BatchSession by updating app tag generation logic to generate appTag always in lowercase characters.
JIRA: https://issues.apache.org/jira/browse/LIVY-978
Verified manually by creating …
> [LIVY-978][SERVER] Update the application tag generation logic in Livy

- server/src/main/scala/org/apache/livy/server/interactive/InteractiveSessionServlet.scala
[LIVY-986][SERVER] Adding null pointer check for SessionInfo
Adding null check for SessionInfo parameters "conf", "archives", "jars", "pyFiles" and "files"
JIRA: https://issues.apache.org/jira/browse/LIVY-986
Tested manually by running session recovery.
Please review https://livy.incubator.apache.org/community/ before opening a pull request.
> [LIVY-986][SERVER] Adding null pointer check for SessionInfo

- dev/merge_livy_pr.py
The `merge_livy_pr`script supports only python 2, which is nowadays not maintained anymore and not even usable in some environments. The PR updates the script so that it support execution on python3 as well.
Manual execution to merge PR #416.
> [DEV] Support python3 in merge_livy_pr script

- dev/third-party-file.ftl
- pom.xml
_Testing build for removed license dependencies_
- Added exclusions to `pom.xml` for relevant Cat X licenses
https://issues.apache.org/jira/browse/LIVY-985
- Unit tests
> Remove unused Cat X licenses

- server/src/test/scala/org/apache/livy/server/batch/BatchServletSpec.scala
- server/src/test/scala/org/apache/livy/server/batch/BatchSessionSpec.scala
Fix print statement in tests to be Python 2 and Python 3 compatible.
https://github.com/apache/incubator-livy/issues/408
Created an account in JIRA, waiting for approval so I can submit a ticket there as well.
Using the docker build for Spark 3
```bash
docker run --rm -it -v $(pwd):/workspace -v $HOME/.m2:/root/.m2 livy-ci mvn package -Pspark3 
```
> Fix testing with Python3

- repl/src/main/scala/org/apache/livy/repl/PythonInterpreter.scala
- repl/src/test/scala/org/apache/livy/repl/PythonInterpreterSpec.scala
When Livy closes PythonInterpreter, the output may not be in JSON format, so there is no need to deserialize json.
https://issues.apache.org/jira/browse/LIVY-995
manual tests
(Please explain how this patch was tested. E.g. unit tests, integration tests, manual tests)
(If this patch involves UI changes, please attach a screenshot; otherwise, remove this)
Please review https://livy.incubator.apache.org/community/ before opening a pull request.
> [LIVY-995][REPL] JsonParseException is thrown when closing Livy session when using python profile

- conf/livy.conf.template
- server/src/main/scala/org/apache/livy/LivyConf.scala
- server/src/main/scala/org/apache/livy/server/recovery/FileSystemStateStore.scala
- server/src/test/scala/org/apache/livy/server/recovery/FileSystemStateStoreSpec.scala
Added safe mode check to implement safe mode
HDFS safe mode is checked when livy session is created. If safe mode is ON, then IllegalStateException is thrown after max retry attempts (configurable) with safe mode interval (configurable) checks are done. If safe mode is OFF, then livy will be able to create session.
https://issues.apache.org/jira/browse/LIVY-977
Added unit test cases to validate code changes. Also, done manual testing in CDP cluster by creating livy sessions with HDFS safe mode check ON/OFF.
> [LIVY-977][SERVER][CONF] Livy can not be started if HDFS is still in safe mode

- thriftserver/server/src/main/scala/org/apache/livy/thriftserver/LivyThriftSessionManager.scala
- thriftserver/server/src/test/scala/org/apache/livy/thriftserver/TestLivyThriftSessionManager.scala
Support connecting to an existing session using the session name via Thrift Server.
JIRA: https://issues.apache.org/jira/browse/LIVY-998
The Thrift Server can set the session name, but it cannot use an existing session name and connect to it. Added the fix to use an existing session name and connect to it via Thrift Server.
Created a session using session name:
```
curl --no-progress-meter -X POST -H "Content-Type: application/json" --data '{"kind": "spark", "name": "sesssionName"}' http://HOST:PORT/sessions
```
Connected to the existing session via Thrift Server using:
```
$ beeline -u "jdbc:hive2://HOST:PORT/?livy.session.name=sesssionName"
```
> [LIVY-998][THRIF] Support connecting to an existing sessions using session name

- server/src/main/scala/org/apache/livy/sessions/SessionManager.scala
Changes done in log info to differentiate session type (interactive or batch) so that it will be easier to identify while deleting sessions
https://issues.apache.org/jira/browse/LIVY-992 
Created both interactive and batch sessions. Then deleted sessions manually with DELETE API. Then checked logs to verify session type
> [LIVY-992][SERVER] In livy logs, user is not able to differentiate between interactive session and batch session

- server/src/main/scala/org/apache/livy/utils/SparkYarnApp.scala
- server/src/test/scala/org/apache/livy/utils/SparkYarnAppSpec.scala
Added conditional check on finished state to set driverlogUrl to null
https://issues.apache.org/jira/browse/LIVY-991 
This patch is tested by adding 2 test cases. One for KILLED application state where both Spark UI URL and driver log url are displayed. Another for FINISHED application state where both Spark UI URL and driver log url are not displayed
> [LIVY-991][SERVER] Facing issues with the Livy UI Driver link

- .gitignore
Add new ignore pattern to .gitignore file for .sdkmanrc file.
https://issues.apache.org/jira/browse/LIVY-997
N/A
> [LIVY-997][DOC] Add file .sdkmanrc to .gitignore

- .github/workflows/integration-tests.yaml
- .github/workflows/unit-tests.yaml
- conf/livy.conf.template
- pom.xml
- rsc/src/main/java/org/apache/livy/rsc/driver/RSCDriver.java
- server/pom.xml
- server/src/main/resources/org/apache/livy/server/ui/static/css/livy-ui.css
- server/src/main/resources/org/apache/livy/server/ui/static/js/all-sessions.js
- server/src/main/resources/org/apache/livy/server/ui/static/js/livy-ui.js
- server/src/main/resources/org/apache/livy/server/ui/static/js/session.js
- server/src/main/scala/org/apache/livy/LivyConf.scala
- server/src/main/scala/org/apache/livy/server/LivyServer.scala
- server/src/main/scala/org/apache/livy/server/interactive/InteractiveSession.scala
- server/src/main/scala/org/apache/livy/sessions/SessionManager.scala
- server/src/main/scala/org/apache/livy/utils/SparkApp.scala
- server/src/main/scala/org/apache/livy/utils/SparkKubernetesApp.scala
- server/src/test/scala/org/apache/livy/utils/SparkKubernetesAppSpec.scala
This pull request (PR) is the foundational PR for adding Kubernetes support in Apache Livy, originally found [here](https://github.com/apache/incubator-livy/pull/249). This update includes a newer version of the Kubernetes client and adds code to display the Spark UI.
This PR introduces a method to submit Spark applications to a Kubernetes cluster. The key points covered include:
- Submitting batch sessions
- Submitting interactive sessions
- Monitoring sessions, collecting logs, and gathering diagnostic information
- Restoring session monitoring after restarts
- Garbage collection (GC) of created Kubernetes resources
JIRA link: https://issues.apache.org/jira/browse/LIVY-702
- **Unit Tests:** The patch has been verified through comprehensive unit tests.
- **Manual Testing:** Conducted …
> [LIVY-702]: Submit Spark apps to Kubernetes

- conf/livy.conf.template
- server/src/main/scala/org/apache/livy/LivyConf.scala
- server/src/main/scala/org/apache/livy/utils/SparkKubernetesApp.scala
- server/src/test/scala/org/apache/livy/utils/SparkKubernetesAppSpec.scala
Instead of spawning a monitor thread for every session, create a centralised thread to monitor all Kubernetes apps.
JIRA link:https://issues.apache.org/jira/browse/LIVY-1007
**Unit Tests:** The patch has been verified through comprehensive unit tests.
**Manual Testing:** Conducted manual testing using Kubernetes on Docker Desktop.
Environment: Helm charts. For detailed instructions on testing using Helm charts, please refer to the documentation available at [livycluster](https://github.com/askhatri/livycluster).
> [LIVY-1007]: Livy should not spawn one thread per job to track the job on Kubernetes

- repl/src/main/resources/fake_shell.py
Description of the problem: https://issues.apache.org/jira/browse/LIVY-863
The proposed fix consists of adding the missing imports that upstream Spark has when it's initiating the Java Gateway.
See the imports of Spark here: https://github.com/apache/spark/blob/87bf6b0ea4ca0618c8604895d05037edce8b7cb0/python/pyspark/java_gateway.py#L153
As far as I am aware, the `java_import()` does not fail or fails silently if the imported class does not exist.
But I might need to add some code to account for different Spark versions, looking for some guidance on this.
If you could please provide some guidance where to add tests for this, I am happy to add them.
> [LIVY-863] Missing JVM class imports for Spark3

- .github/workflows/build-ci-image.yaml
- .github/workflows/integration-tests.yaml
- .github/workflows/unit-tests.yaml
- dev/docker/livy-dev-base/Dockerfile
- integration-test/src/test/resources/test_python_api.py
- integration-test/src/test/scala/org/apache/livy/test/BatchIT.scala
- integration-test/src/test/scala/org/apache/livy/test/InteractiveIT.scala
- repl/src/test/scala/org/apache/livy/repl/PythonInterpreterSpec.scala
The CI environment is broken due to library version conflicts between the image and the checkout action.
The livy-ci Docker image needs to be upgraded to a more recent version of Ubuntu, ensuring that the unit tests and integration tests all pass.
Due to a bug in Livy's GitHub workflows, tests had only been executed with Spark 2. Now that this is fixed, we also need to make updates to some of the Python-based tests to work with Python 3 because Spark 3.2 does not support Python 2.
Two R-based integration tests are ignored in the Spark 2 integration test runs because SparkR 2 does not work with R 4, and the last version of Ubuntu with R 3.6 is Ubuntu 20. If we want to re-enable these tests, we may need to build R 3.6 for Ubuntu 24.
CI and unit test runs in a private fork of the repo.
> [LIVY-1011] Upgrade CI image, fix Spark 3 tests

- conf/livy.conf.template
- server/src/main/scala/org/apache/livy/LivyConf.scala
- server/src/main/scala/org/apache/livy/server/LivyServer.scala
- server/src/main/scala/org/apache/livy/server/SecurityHeadersFilter.scala
- server/src/test/scala/org/apache/livy/server/SecurityHeadersFilterSpec.scala
This change introduces a new configuration option `livy.server.security-headers.enabled`.
When this property is set to true, the following security headers are added to HTTP
responses by default:
* X-XSS-Protection
* X-Frame-Options
* X-Content-Type-Options
* Strict-Transport-Security
* Content-Security-Policy
Also, adds content type information to all responses as required when using content type option nosniff
Tested manually
> [LIVY-785] Enable adding security related HTTP headers

- server/src/main/scala/org/apache/livy/server/WebServer.scala
- thriftserver/server/src/main/scala/org/apache/livy/thriftserver/cli/ThriftHttpCLIService.scala
Use SslContextFactory.Server() instead of SslContextFactory() when constructing the factory.
With Jetty 9.4.50, we should call SslContextFactory.Server(), instead of SslContextFactory(), to create SslContextFactory. Otherwise we get the following error when using a KeyStore with multiple certificates in it.
```
Exception in thread "main" java.lang.IllegalStateException: KeyStores with multiple certificates are not supported on the base class org.eclipse.jetty.util.ssl.SslContextFactory. (Use org.eclipse.jetty.util.ssl.
SslContextFactory$Server or org.eclipse.jetty.util.ssl.SslContextFactory$Client instead)
at org.eclipse.jetty.util.ssl.SslContextFactory.newSniX509ExtendedKeyManager(SslContextFactory.java:1289)
```
Please review https://livy.incubator.apache.org/community/ before opening a …
> [LIVY-1012] Use SslContextFactory.Server() instead of SslContextFactory

- docs/rest-api.md
`cursor` request parameter is integer, not string:
https://github.com/apache/incubator-livy/blob/86fc823/core/src/main/scala/org/apache/livy/msgs.scala#L63
> [MINOR][DOC] Fix cursor parameter documentation for completion endpoint
